// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ceshi1Builder.proto

package com.game.proto.ceshi;

public final class Ceshi1Builder {
  private Ceshi1Builder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Ceshi1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.proto.ceshi.Ceshi1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
     */
    int getHilarityValue();
    /**
     * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
     */
    Ceshi1.Humour getHilarity();

    /**
     * <code>int32 height_in_cm = 3;</code>
     */
    int getHeightInCm();

    /**
     * <code>bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int64 result_count = 7;</code>
     */
    long getResultCount();

    /**
     * <code>bool true_scotsman = 8;</code>
     */
    boolean getTrueScotsman();

    /**
     * <code>float score = 9;</code>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code com.game.proto.ceshi.Ceshi1}
   */
  public  static final class Ceshi1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.proto.ceshi.Ceshi1)
      Ceshi1OrBuilder {
    // Use Ceshi1.newBuilder() to construct.
    private Ceshi1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ceshi1() {
      name_ = "";
      hilarity_ = 0;
      heightInCm_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      resultCount_ = 0L;
      trueScotsman_ = false;
      score_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ceshi1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              hilarity_ = rawValue;
              break;
            }
            case 24: {

              heightInCm_ = input.readInt32();
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            case 56: {

              resultCount_ = input.readInt64();
              break;
            }
            case 64: {

              trueScotsman_ = input.readBool();
              break;
            }
            case 77: {

              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ceshi1Builder.internal_static_com_game_proto_ceshi_Ceshi1_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ceshi1Builder.internal_static_com_game_proto_ceshi_Ceshi1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Ceshi1.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.game.proto.ceshi.Ceshi1.Humour}
     */
    public enum Humour
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>PUNS = 1;</code>
       */
      PUNS(1),
      /**
       * <code>SLAPSTICK = 2;</code>
       */
      SLAPSTICK(2),
      /**
       * <code>BILL_BAILEY = 3;</code>
       */
      BILL_BAILEY(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>PUNS = 1;</code>
       */
      public static final int PUNS_VALUE = 1;
      /**
       * <code>SLAPSTICK = 2;</code>
       */
      public static final int SLAPSTICK_VALUE = 2;
      /**
       * <code>BILL_BAILEY = 3;</code>
       */
      public static final int BILL_BAILEY_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Humour valueOf(int value) {
        return forNumber(value);
      }

      public static Humour forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return PUNS;
          case 2: return SLAPSTICK;
          case 3: return BILL_BAILEY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Humour>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Humour> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Humour>() {
              public Humour findValueByNumber(int number) {
                return Humour.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Ceshi1.getDescriptor().getEnumTypes().get(0);
      }

      private static final Humour[] VALUES = values();

      public static Humour valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Humour(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.game.proto.ceshi.Ceshi1.Humour)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HILARITY_FIELD_NUMBER = 2;
    private int hilarity_;
    /**
     * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
     */
    public int getHilarityValue() {
      return hilarity_;
    }
    /**
     * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
     */
    public Humour getHilarity() {
      Humour result = Humour.valueOf(hilarity_);
      return result == null ? Humour.UNRECOGNIZED : result;
    }

    public static final int HEIGHT_IN_CM_FIELD_NUMBER = 3;
    private int heightInCm_;
    /**
     * <code>int32 height_in_cm = 3;</code>
     */
    public int getHeightInCm() {
      return heightInCm_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int RESULT_COUNT_FIELD_NUMBER = 7;
    private long resultCount_;
    /**
     * <code>int64 result_count = 7;</code>
     */
    public long getResultCount() {
      return resultCount_;
    }

    public static final int TRUE_SCOTSMAN_FIELD_NUMBER = 8;
    private boolean trueScotsman_;
    /**
     * <code>bool true_scotsman = 8;</code>
     */
    public boolean getTrueScotsman() {
      return trueScotsman_;
    }

    public static final int SCORE_FIELD_NUMBER = 9;
    private float score_;
    /**
     * <code>float score = 9;</code>
     */
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (hilarity_ != Humour.UNKNOWN.getNumber()) {
        output.writeEnum(2, hilarity_);
      }
      if (heightInCm_ != 0) {
        output.writeInt32(3, heightInCm_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      if (resultCount_ != 0L) {
        output.writeInt64(7, resultCount_);
      }
      if (trueScotsman_ != false) {
        output.writeBool(8, trueScotsman_);
      }
      if (score_ != 0F) {
        output.writeFloat(9, score_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (hilarity_ != Humour.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, hilarity_);
      }
      if (heightInCm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heightInCm_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (resultCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, resultCount_);
      }
      if (trueScotsman_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, trueScotsman_);
      }
      if (score_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, score_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Ceshi1)) {
        return super.equals(obj);
      }
      Ceshi1 other = (Ceshi1) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && hilarity_ == other.hilarity_;
      result = result && (getHeightInCm()
          == other.getHeightInCm());
      result = result && getData()
          .equals(other.getData());
      result = result && (getResultCount()
          == other.getResultCount());
      result = result && (getTrueScotsman()
          == other.getTrueScotsman());
      result = result && (
          Float.floatToIntBits(getScore())
          == Float.floatToIntBits(
              other.getScore()));
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HILARITY_FIELD_NUMBER;
      hash = (53 * hash) + hilarity_;
      hash = (37 * hash) + HEIGHT_IN_CM_FIELD_NUMBER;
      hash = (53 * hash) + getHeightInCm();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + RESULT_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResultCount());
      hash = (37 * hash) + TRUE_SCOTSMAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTrueScotsman());
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ceshi1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ceshi1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ceshi1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ceshi1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ceshi1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ceshi1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ceshi1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Ceshi1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ceshi1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Ceshi1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ceshi1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Ceshi1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ceshi1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ceshi.Ceshi1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.proto.ceshi.Ceshi1)
        Ceshi1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Ceshi1Builder.internal_static_com_game_proto_ceshi_Ceshi1_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Ceshi1Builder.internal_static_com_game_proto_ceshi_Ceshi1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Ceshi1.class, Builder.class);
      }

      // Construct using com.game.proto.ceshi.Ceshi1Builder.Ceshi1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        hilarity_ = 0;

        heightInCm_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        resultCount_ = 0L;

        trueScotsman_ = false;

        score_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Ceshi1Builder.internal_static_com_game_proto_ceshi_Ceshi1_descriptor;
      }

      public Ceshi1 getDefaultInstanceForType() {
        return Ceshi1.getDefaultInstance();
      }

      public Ceshi1 build() {
        Ceshi1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Ceshi1 buildPartial() {
        Ceshi1 result = new Ceshi1(this);
        result.name_ = name_;
        result.hilarity_ = hilarity_;
        result.heightInCm_ = heightInCm_;
        result.data_ = data_;
        result.resultCount_ = resultCount_;
        result.trueScotsman_ = trueScotsman_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ceshi1) {
          return mergeFrom((Ceshi1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ceshi1 other) {
        if (other == Ceshi1.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hilarity_ != 0) {
          setHilarityValue(other.getHilarityValue());
        }
        if (other.getHeightInCm() != 0) {
          setHeightInCm(other.getHeightInCm());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getResultCount() != 0L) {
          setResultCount(other.getResultCount());
        }
        if (other.getTrueScotsman() != false) {
          setTrueScotsman(other.getTrueScotsman());
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Ceshi1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Ceshi1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int hilarity_ = 0;
      /**
       * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
       */
      public int getHilarityValue() {
        return hilarity_;
      }
      /**
       * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
       */
      public Builder setHilarityValue(int value) {
        hilarity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
       */
      public Humour getHilarity() {
        Humour result = Humour.valueOf(hilarity_);
        return result == null ? Humour.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
       */
      public Builder setHilarity(Humour value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        hilarity_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.game.proto.ceshi.Ceshi1.Humour hilarity = 2;</code>
       */
      public Builder clearHilarity() {
        
        hilarity_ = 0;
        onChanged();
        return this;
      }

      private int heightInCm_ ;
      /**
       * <code>int32 height_in_cm = 3;</code>
       */
      public int getHeightInCm() {
        return heightInCm_;
      }
      /**
       * <code>int32 height_in_cm = 3;</code>
       */
      public Builder setHeightInCm(int value) {
        
        heightInCm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height_in_cm = 3;</code>
       */
      public Builder clearHeightInCm() {
        
        heightInCm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long resultCount_ ;
      /**
       * <code>int64 result_count = 7;</code>
       */
      public long getResultCount() {
        return resultCount_;
      }
      /**
       * <code>int64 result_count = 7;</code>
       */
      public Builder setResultCount(long value) {
        
        resultCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 result_count = 7;</code>
       */
      public Builder clearResultCount() {
        
        resultCount_ = 0L;
        onChanged();
        return this;
      }

      private boolean trueScotsman_ ;
      /**
       * <code>bool true_scotsman = 8;</code>
       */
      public boolean getTrueScotsman() {
        return trueScotsman_;
      }
      /**
       * <code>bool true_scotsman = 8;</code>
       */
      public Builder setTrueScotsman(boolean value) {
        
        trueScotsman_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool true_scotsman = 8;</code>
       */
      public Builder clearTrueScotsman() {
        
        trueScotsman_ = false;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 9;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 9;</code>
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 9;</code>
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.game.proto.ceshi.Ceshi1)
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ceshi.Ceshi1)
    private static final Ceshi1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ceshi1();
    }

    public static Ceshi1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ceshi1>
        PARSER = new com.google.protobuf.AbstractParser<Ceshi1>() {
      public Ceshi1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ceshi1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ceshi1> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Ceshi1> getParserForType() {
      return PARSER;
    }

    public Ceshi1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ceshi_Ceshi1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_proto_ceshi_Ceshi1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023Ceshi1Builder.proto\022\024com.game.proto.ce" +
      "shi\"\356\001\n\006Ceshi1\022\014\n\004name\030\001 \001(\t\0225\n\010hilarity" +
      "\030\002 \001(\0162#.com.game.proto.ceshi.Ceshi1.Hum" +
      "our\022\024\n\014height_in_cm\030\003 \001(\005\022\014\n\004data\030\004 \001(\014\022" +
      "\024\n\014result_count\030\007 \001(\003\022\025\n\rtrue_scotsman\030\010" +
      " \001(\010\022\r\n\005score\030\t \001(\002\"?\n\006Humour\022\013\n\007UNKNOWN" +
      "\020\000\022\010\n\004PUNS\020\001\022\r\n\tSLAPSTICK\020\002\022\017\n\013BILL_BAIL" +
      "EY\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_proto_ceshi_Ceshi1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_proto_ceshi_Ceshi1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_proto_ceshi_Ceshi1_descriptor,
        new String[] { "Name", "Hilarity", "HeightInCm", "Data", "ResultCount", "TrueScotsman", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
