// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoCeshiBuilder.proto

package com.game.proto.ceshi;

public final class ProtoCeshiBuilder {
  private ProtoCeshiBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoCeshiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.proto.ceshi.ProtoCeshi)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 pid = 2;</code>
     */
    int getPid();

    /**
     * <code>int64 lid = 3;</code>
     */
    long getLid();

    /**
     * <code>bool valid = 4;</code>
     */
    boolean getValid();

    /**
     * <code>float score = 5;</code>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code com.game.proto.ceshi.ProtoCeshi}
   */
  public  static final class ProtoCeshi extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.proto.ceshi.ProtoCeshi)
      ProtoCeshiOrBuilder {
    // Use ProtoCeshi.newBuilder() to construct.
    private ProtoCeshi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoCeshi() {
      name_ = "";
      pid_ = 0;
      lid_ = 0L;
      valid_ = false;
      score_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoCeshi(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              pid_ = input.readInt32();
              break;
            }
            case 24: {

              lid_ = input.readInt64();
              break;
            }
            case 32: {

              valid_ = input.readBool();
              break;
            }
            case 45: {

              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoCeshiBuilder.internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoCeshiBuilder.internal_static_com_game_proto_ceshi_ProtoCeshi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoCeshi.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PID_FIELD_NUMBER = 2;
    private int pid_;
    /**
     * <code>int32 pid = 2;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int LID_FIELD_NUMBER = 3;
    private long lid_;
    /**
     * <code>int64 lid = 3;</code>
     */
    public long getLid() {
      return lid_;
    }

    public static final int VALID_FIELD_NUMBER = 4;
    private boolean valid_;
    /**
     * <code>bool valid = 4;</code>
     */
    public boolean getValid() {
      return valid_;
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private float score_;
    /**
     * <code>float score = 5;</code>
     */
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (pid_ != 0) {
        output.writeInt32(2, pid_);
      }
      if (lid_ != 0L) {
        output.writeInt64(3, lid_);
      }
      if (valid_ != false) {
        output.writeBool(4, valid_);
      }
      if (score_ != 0F) {
        output.writeFloat(5, score_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pid_);
      }
      if (lid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lid_);
      }
      if (valid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, valid_);
      }
      if (score_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, score_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoCeshi)) {
        return super.equals(obj);
      }
      ProtoCeshi other = (ProtoCeshi) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getPid()
          == other.getPid());
      result = result && (getLid()
          == other.getLid());
      result = result && (getValid()
          == other.getValid());
      result = result && (
          Float.floatToIntBits(getScore())
          == Float.floatToIntBits(
              other.getScore()));
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + LID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLid());
      hash = (37 * hash) + VALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getValid());
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoCeshi parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCeshi parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCeshi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCeshi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCeshi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCeshi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCeshi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCeshi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoCeshi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoCeshi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoCeshi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCeshi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoCeshi prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ceshi.ProtoCeshi}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.proto.ceshi.ProtoCeshi)
        ProtoCeshiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoCeshiBuilder.internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoCeshiBuilder.internal_static_com_game_proto_ceshi_ProtoCeshi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoCeshi.class, Builder.class);
      }

      // Construct using com.game.proto.ceshi.ProtoCeshiBuilder.ProtoCeshi.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        pid_ = 0;

        lid_ = 0L;

        valid_ = false;

        score_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoCeshiBuilder.internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor;
      }

      public ProtoCeshi getDefaultInstanceForType() {
        return ProtoCeshi.getDefaultInstance();
      }

      public ProtoCeshi build() {
        ProtoCeshi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoCeshi buildPartial() {
        ProtoCeshi result = new ProtoCeshi(this);
        result.name_ = name_;
        result.pid_ = pid_;
        result.lid_ = lid_;
        result.valid_ = valid_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoCeshi) {
          return mergeFrom((ProtoCeshi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoCeshi other) {
        if (other == ProtoCeshi.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (other.getLid() != 0L) {
          setLid(other.getLid());
        }
        if (other.getValid() != false) {
          setValid(other.getValid());
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoCeshi parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoCeshi) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>int32 pid = 2;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>int32 pid = 2;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pid = 2;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private long lid_ ;
      /**
       * <code>int64 lid = 3;</code>
       */
      public long getLid() {
        return lid_;
      }
      /**
       * <code>int64 lid = 3;</code>
       */
      public Builder setLid(long value) {
        
        lid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lid = 3;</code>
       */
      public Builder clearLid() {
        
        lid_ = 0L;
        onChanged();
        return this;
      }

      private boolean valid_ ;
      /**
       * <code>bool valid = 4;</code>
       */
      public boolean getValid() {
        return valid_;
      }
      /**
       * <code>bool valid = 4;</code>
       */
      public Builder setValid(boolean value) {
        
        valid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool valid = 4;</code>
       */
      public Builder clearValid() {
        
        valid_ = false;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 5;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 5;</code>
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 5;</code>
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.game.proto.ceshi.ProtoCeshi)
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ceshi.ProtoCeshi)
    private static final ProtoCeshi DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoCeshi();
    }

    public static ProtoCeshi getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoCeshi>
        PARSER = new com.google.protobuf.AbstractParser<ProtoCeshi>() {
      public ProtoCeshi parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoCeshi(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoCeshi> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoCeshi> getParserForType() {
      return PARSER;
    }

    public ProtoCeshi getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_proto_ceshi_ProtoCeshi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027ProtoCeshiBuilder.proto\022\024com.game.prot" +
      "o.ceshi\"R\n\nProtoCeshi\022\014\n\004name\030\001 \001(\t\022\013\n\003p" +
      "id\030\002 \001(\005\022\013\n\003lid\030\003 \001(\003\022\r\n\005valid\030\004 \001(\010\022\r\n\005" +
      "score\030\005 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_proto_ceshi_ProtoCeshi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_proto_ceshi_ProtoCeshi_descriptor,
        new String[] { "Name", "Pid", "Lid", "Valid", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
