// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCodeBuilder.proto

package com.game.proto.error;

public final class ErrorCodeBuilder {
  private ErrorCodeBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.proto.error.ErrorCode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 commandId = 1;</code>
     */
    boolean hasCommandId();
    /**
     * <code>required int32 commandId = 1;</code>
     */
    int getCommandId();

    /**
     * <code>required int32 errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>required int32 errorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    java.util.List<String>
        getErrorArgsList();
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    int getErrorArgsCount();
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    String getErrorArgs(int index);
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorArgsBytes(int index);
  }
  /**
   * Protobuf type {@code com.game.proto.error.ErrorCode}
   */
  public  static final class ErrorCode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.proto.error.ErrorCode)
      ErrorCodeOrBuilder {
    // Use ErrorCode.newBuilder() to construct.
    private ErrorCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorCode() {
      commandId_ = 0;
      errorCode_ = 0;
      errorArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorCode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                errorArgs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              errorArgs_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          errorArgs_ = errorArgs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ErrorCodeBuilder.internal_static_com_game_proto_error_ErrorCode_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ErrorCodeBuilder.internal_static_com_game_proto_error_ErrorCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ErrorCode.class, Builder.class);
    }

    private int bitField0_;
    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>required int32 commandId = 1;</code>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 commandId = 1;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>required int32 errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 errorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList errorArgs_;
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getErrorArgsList() {
      return errorArgs_;
    }
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    public int getErrorArgsCount() {
      return errorArgs_.size();
    }
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    public String getErrorArgs(int index) {
      return errorArgs_.get(index);
    }
    /**
     * <code>repeated string errorArgs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorArgsBytes(int index) {
      return errorArgs_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommandId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorCode_);
      }
      for (int i = 0; i < errorArgs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorArgs_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorArgs_.size(); i++) {
          dataSize += computeStringSizeNoTag(errorArgs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrorArgsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ErrorCode)) {
        return super.equals(obj);
      }
      ErrorCode other = (ErrorCode) obj;

      boolean result = true;
      result = result && (hasCommandId() == other.hasCommandId());
      if (hasCommandId()) {
        result = result && (getCommandId()
            == other.getCommandId());
      }
      result = result && (hasErrorCode() == other.hasErrorCode());
      if (hasErrorCode()) {
        result = result && (getErrorCode()
            == other.getErrorCode());
      }
      result = result && getErrorArgsList()
          .equals(other.getErrorArgsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommandId()) {
        hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
        hash = (53 * hash) + getCommandId();
      }
      if (hasErrorCode()) {
        hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode();
      }
      if (getErrorArgsCount() > 0) {
        hash = (37 * hash) + ERRORARGS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorArgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ErrorCode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorCode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ErrorCode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.error.ErrorCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.proto.error.ErrorCode)
        ErrorCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ErrorCodeBuilder.internal_static_com_game_proto_error_ErrorCode_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ErrorCodeBuilder.internal_static_com_game_proto_error_ErrorCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ErrorCode.class, Builder.class);
      }

      // Construct using com.game.proto.error.ErrorCodeBuilder.ErrorCode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ErrorCodeBuilder.internal_static_com_game_proto_error_ErrorCode_descriptor;
      }

      public ErrorCode getDefaultInstanceForType() {
        return ErrorCode.getDefaultInstance();
      }

      public ErrorCode build() {
        ErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ErrorCode buildPartial() {
        ErrorCode result = new ErrorCode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          errorArgs_ = errorArgs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.errorArgs_ = errorArgs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ErrorCode) {
          return mergeFrom((ErrorCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ErrorCode other) {
        if (other == ErrorCode.getDefaultInstance()) return this;
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.errorArgs_.isEmpty()) {
          if (errorArgs_.isEmpty()) {
            errorArgs_ = other.errorArgs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureErrorArgsIsMutable();
            errorArgs_.addAll(other.errorArgs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommandId()) {
          return false;
        }
        if (!hasErrorCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ErrorCode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ErrorCode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int commandId_ ;
      /**
       * <code>required int32 commandId = 1;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 commandId = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>required int32 commandId = 1;</code>
       */
      public Builder setCommandId(int value) {
        bitField0_ |= 0x00000001;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 commandId = 1;</code>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>required int32 errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 errorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>required int32 errorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList errorArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureErrorArgsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          errorArgs_ = new com.google.protobuf.LazyStringArrayList(errorArgs_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getErrorArgsList() {
        return errorArgs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public int getErrorArgsCount() {
        return errorArgs_.size();
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public String getErrorArgs(int index) {
        return errorArgs_.get(index);
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorArgsBytes(int index) {
        return errorArgs_.getByteString(index);
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public Builder setErrorArgs(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorArgsIsMutable();
        errorArgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public Builder addErrorArgs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorArgsIsMutable();
        errorArgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public Builder addAllErrorArgs(
          Iterable<String> values) {
        ensureErrorArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorArgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public Builder clearErrorArgs() {
        errorArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorArgs = 3;</code>
       */
      public Builder addErrorArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorArgsIsMutable();
        errorArgs_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.proto.error.ErrorCode)
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.error.ErrorCode)
    private static final ErrorCode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ErrorCode();
    }

    public static ErrorCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ErrorCode>
        PARSER = new com.google.protobuf.AbstractParser<ErrorCode>() {
      public ErrorCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorCode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorCode> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ErrorCode> getParserForType() {
      return PARSER;
    }

    public ErrorCode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_error_ErrorCode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_proto_error_ErrorCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026ErrorCodeBuilder.proto\022\024com.game.proto" +
      ".error\"D\n\tErrorCode\022\021\n\tcommandId\030\001 \002(\005\022\021" +
      "\n\terrorCode\030\002 \002(\005\022\021\n\terrorArgs\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_proto_error_ErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_proto_error_ErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_proto_error_ErrorCode_descriptor,
        new String[] { "CommandId", "ErrorCode", "ErrorArgs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
